### ISSUE TITLE
Add lists to zbot

### ISSUE THREAD

**Issue by fimad** [numberten/zhenya_bot#10]
I want to be able to do:

!list add ggpj write basic ircd

!list

> ggpj
> list2

!list show ggpj

> 1) foo
> 2) bar

!list rm ggpj 1

> 1) bar

!list rmlist ggpj

**Comment by numberten** [comment]
I'm thinking valid syntax would be:
--Display usage message
!list
--Display list of list names, or elements in given list if optional param provided
!list show [list_name]
--Adds new list to list of lists
!list add list_name 
--Adds new element to given list
!list cons list_name element
--Removes list from list of lists
!list rmlist list_name
--Removes element from given list
!list rm list_name element_number

Anything else? Does order matter for our lists? We could add a snoc or make it so you add to a particular index.

**Comment by numberten** [comment]
We could also consolidate syntax by making [element] an optional for param for rm and add like this:
!list add list_name [element]
!list rm list_name [element]

Where they add/remove lists from the list of list, or elements from the given list when an element is provided.

**Comment by fimad** [comment]
+1 for the consolidated syntax for adding and removing.

Do we want to support fancier features like searching or marking an element in a list as done?

**Comment by numberten** [comment]
Not sure about searching, I feel like that is something we could come back to and add if we ever feel a pressing need for it.

I like the idea of being able to mark things off as done.

**Comment by numberten** [comment]
Still todo:
- ~~Marking elements as done~~
- ~~Insertion at given indexes~~
