### ISSUE TITLE
!queens: denial of service 

### ISSUE THREAD

**Issue by numberten** [numberten/zhenya_bot#19]
Large inputs force zhenya_bot to freeze as it calculates an answer.

Solution: Putting a hard limit on valid values of n.

**Comment by keneanung** [comment]
This can be easily done with a guard as it was in the non optimed version (https://github.com/numberten/zhenya_bot/commit/89f9f7fd29255b162466da82f26f289e3ed5b0a0#diff-c27c8b224406b83537d38923ef7a179eR20)

**Comment by numberten** [comment]
Sounds good

**Comment by numberten** [comment]
Pull request #21 closes this.
