### ISSUE TITLE
README is out of date

### ISSUE THREAD

**Issue by numberten** [numberten/zhenya_bot#24]
README could use a redo.

Things we're missing:
- ~~installation guide~~
- ~~up-to-date syntax for commands~~
- ~~a license~~
- ~~compatibility~~

**Comment by numberten** [comment]
42539c5 added MIT license

**Comment by numberten** [comment]
No longer sure if the passive component section is necessary for the v1.0 readme.

The command section might be something we can either move to a different markdown file, or drop completely upon implementation of #31.

Eventually it might be worth expanding upon documentation and making a new file along the lines of "how to roll your own component" that talks about passive services and such.

@fimad thoughts?

**Comment by fimad** [comment]
Yeah I think we probably don't need to list out every command if we implement the !man command or something similar. We could probably condense that section into something that talks more generally about the extensible of the component system with some examples maybe.

I think a how to roll your own component is a good idea. We might want to turn an example component into literate haskell file.

**Comment by numberten** [comment]
Then we're finished with the README as of 1.0. Our next steps documentation wise will be taken care of by #31 and #32, which address end-users at runtime and component developers respectively.
