### ISSUE TITLE
Should restart if the server goes down. 

### ISSUE THREAD

**Issue by fimad** [numberten/zhenya_bot#25]
Currently the bot does not detect server crashes. Zhenya_bot should either detect a broken socket or periodically send pings and restart itself if the server does not send a pong message in a reasonable amount of time.

**Comment by fimad** [comment]
I think this may actually not be an issue...

**Comment by numberten** [comment]
Any further information on whether or not this is an issue?

**Comment by fimad** [comment]
Closing for now, will reopen if the problem is observed.
