### ISSUE TITLE
Enforce usage messages

### ISSUE THREAD

**Issue by numberten** [numberten/zhenya_bot#30]
For the sake of transparency for end users, it is best practice for all active components to have a usage message when invoked without any parameters. It would be convenient if this were enforced by the type system, instead of leaving it up to the component's implementer to remember to catch the edge case.

**Comment by numberten** [comment]
I think a good place for this might be adding an additional String parameter (the usage message) to `command` and `commandT` in Command.hs

**Comment by SWPhantom** [comment]
Wouldn't work with certain commands, like !oprah, obviously. Could we include a big help text? "!man"?

**Comment by numberten** [comment]
The commands in the Op component (!oprah, !ding, !ascend) use `simpleCommandT` for their construction. `command` and `commandT` are only used for components that require arguments.

I think a man/help component that displays a list of commands or information regarding the specific use of a individual command is a good idea. It could probably use its own issue.
