### ISSUE TITLE
buttbot component

### ISSUE THREAD

**Issue by TranquilMarmot** [numberten/zhenya_bot#49]
We all remember the wonderful buttbot. If you don't, check out https://code.google.com/p/buttbot/

Basically, at random, buttbot will take a sentence and replace a word with 'butt'. Results can be hilarious.

Only issue I ever had with buttbot was that sometimes it would be a little too active. I'm thinking maybe a !butt command will take the last said line and butt-ify it.

![image](https://cloud.githubusercontent.com/assets/504259/3739974/53df8568-1750-11e4-95c5-4d14f86d94c7.png)

**Comment by numberten** [comment]
Funnier when syllables are replaced instead of words. Could throw together something that queries http://www.howmanysyllables.com/, but it would probably be more fitting to just wait on #40.
