### ISSUE TITLE
ircWrite newline error

### ISSUE THREAD

**Issue by numberten** [numberten/zhenya_bot#5]
ircWrite breaks on newlines as shown:

23:27 @jesse !define london
23:27 @zhenya_bot london: The Capital of the world, only rival New York. Incorporates the best of both Europe and America. Unlike in New York the Tube stations are 
                    Clearly signposted. Unlike New York the streets are all squigley and it is really really old. South of the river Thames is a mythical land that those 
                    on the North talk about in nervous whispers, but it actually isn't that bad and is fast becoming the only place in the city besides cardboard boxes th
23:27 @zhenya_bot at is affordable to live in. Stand in the middle of the Millenium footbridge and turn around in a 360 degree circle. Go on the London eye. Don't 
                    visit the London Dungeons. Go shopping on portabello road, or in Camden, not in Covent Garden. Go to the opera in Regent's park, and to speaker's 
                    corner in Hyde park on a sunday afternoon. Trafalger Square in the evening, Leicester square at mid-day. Karl Marx and Charles Dickens are buried in 
                    Highga
23:27 @zhenya_bot te cemetary. Ealing is queen of the suburbs.
23:27 @jesse now..
23:27 @jesse !define 666
23:27 @zhenya_bot 666: The Mark of the beast, and the men who follow the beast of the earth will bear this mark to display their allegiance to the beast. It has been 
                    disputed by some scholars that certain numeric ciphers would translate it over to certain words, names, etc... For example, one of the more popular 
                    translations was Nero Caesar, and before that, Lateinos, etc...
23:27 @zhenya_bot ect number to represent the impurities of man and their evildoings and sinful ways.
23:27 @jesse it drops some stuff
23:27 @jesse usually it stops reading on new line breaks
23:27 @jesse !define trogdor
23:27 @zhenya_bot trogdor: Trogdor:
23:27 @zhenya_bot e countryside and the peasants who inhabit it, he is also known by his full name, "Trogdor the Burninator".
23:27 @will ah
23:27 @jesse o.o
23:27 @jesse anything with newlines

**Comment by will** [comment]
ah

**Comment by numberten** [comment]
um.

**Comment by numberten** [comment]
oh were you notified by that comment? sorry about that
